application_name: Algebananazzzzz
deployment:
  target_bucket: algebananazzzzz-portfolio-s3
  domain:
    zone_id: Z0988667CU38UWRZ0UHD
    aliases:
      - algebananazzzzz.com
    viewer_certificate: arn:aws:acm:us-east-1:165322143606:certificate/320b9850-2c72-4ef0-a9d1-84cbe4149684